- hosts: "{{ IP }}"
  connection: local
  gather_facts: False
  vars:
  tasks:
    - name: ssh facts
      register: iosfacts_out
      ios_facts:
        gather_subset: interfaces 
    - debug: 
        msg: "{{ iosfacts_out | to_nice_json }}"
