- hosts: "{{ IP }}"
  connection: local
  vars:
  tasks:
    - name: ssh facts
      register: iosfacts_out
      ios_facts:
        gather_subset: all
    - debug: 
        msg: "{{ iosfacts_out[ansible_net_interfaces] | to_nice_json }}"
