- hosts: "{{ IP }}"
  connection: local
  gather_facts: False
  vars:
  tasks:
    - name: ssh facts
      register: iosfacts_out
      ios_facts:
        gather_subset: 
          - interfaces 
          - '!hardware'
    - debug: 
        msg: "{{ iosfacts_out[ansible_facts] }}"
