---
- hosts: "{{ hostname }}"
  connection: local
  gather_facts: False

  tasks:
    - name: SET VLAN ON PORT
      ios_l2_interface:
        name: "GigabitEthernet{{ switchNum }}/0/{{ portNum }}"
        access_vlan: {{ vlan }}
        mode: access
