---
- name: Test VLAN
  hosts: 10.147.247.230
  ansible_connection: network_cli
  ansible_network_os: ios

 
  tasks:
 
  - name: SET VLAN ON PORT
    ios_l2_interface:
      name: GigabitEthernet1/0/13
      access_vlan: 2005
      mode: access
