---
- name: Test VLAN
  hosts: 10.147.247.230
  connection: local
  gather_facts: false
  
  tasks:
 
  - name: SET VLAN ON PORT
    ios_l2_interface:
      name: "{{ interface }}"
      access_vlan: "{{ vlan }}"
      mode: access
